# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-04 14:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timer', '0002_auto_20161103_1825'),
    ]

    operations = [
        migrations.AddField(
            model_name='stay',
            name='notes',
            field=models.TextField(null=True),
        ),
    ]
